#Following line was generated by
#python -c "import os; from glob import glob; print [y for x in os.walk('./data') for y in glob(os.path.join(x[0], '*.xlsx'))]"
#['./data/PG/MTech-3yr/CS-MTech3yr.xlsx', 
#['./data/PG/MTech-3yr/ME-MTech3yr.xlsx', './data/PG/MTech-3yr/CE-MTech3yr.xlsx', './data/PG/PhD/MS-PhD.xlsx', './data/PG/PhD/ME-PhD.xlsx', './data/PG/PhD/DS-PhD.xlsx', './data/PG/PhD/CY-PhD.xlsx', './data/PG/PhD/LA-PhD.xlsx', './data/PG/PhD/CS-PhD-Direct.xlsx', './data/PG/PhD/CS-PhD.xlsx', './data/PG/PhD/CHE-PhD.xlsx', './data/PG/MTech-2yr/ME-MTech2yr-MAD.xlsx', './data/PG/MTech-2yr/CHE-MTech2yr.xlsx', './data/PG/MTech-2yr/PH-MSc2yr.xlsx', './data/PG/MTech-2yr/CE-MTech2yr-Geo.xlsx', './data/PG/MTech-2yr/CY-MSc2yr.xlsx', './data/PG/MTech-2yr/ME-MTech2yr-FES.xlsx', './data/PG/MTech-2yr/CE-MTech2yr-Struct.xlsx', './data/PG/MTech-2yr/DS-MDes2yr.xlsx', './data/PG/MTech-2yr/MS-MTech2yr.xlsx', './data/PG/MTech-2yr/EE-MTech2yr-Micro.xlsx', './data/PG/MTech-2yr/MA-MSc2yr-PhD.xlsx', './data/PG/MTech-2yr/CS-MTech2yr.xlsx', './data/PG/MTech-2yr/ME-MTech2yr-IDM.xlsx', './data/PG/MTech-2yr/BT-MTech2yr-PhD.xlsx', './data/PG/MTech-2yr/CE-MTech2yr-EWRE.xlsx', './data/PG/MTech-1yr/ME-MTech1yr-MAD.xlsx', './data/PG/MTech-1yr/EE-MTech1yr-Micro.xlsx', './data/PG/MTech-1yr/MS-MTech1yr.xlsx', './data/PG/MTech-1yr/MS-MTech1yr-Thesis.xlsx', './data/PG/MTech-1yr/ME-MTech1yr-IDM.xlsx', './data/PG/MTech-1yr/CS-MTech1yr-MDS.xlsx', './data/PG/MTech-1yr/ME-MTech1yr-FES.xlsx', './data/UG/MA-BTech.xlsx', './data/UG/CHE-BTech.xlsx', './data/UG/ME-BTech.xlsx', './data/UG/EE-BTech.xlsx', './data/UG/CE-BTech.xlsx', './data/UG/ES-BTech.xlsx', './data/UG/CY-BTech.xlsx', './data/UG/PH-BTech.xlsx', './data/UG/DS-BDes.xlsx', './data/UG/CS-BTech.xlsx', './data/UG/LA-BTech.xlsx', './data/UG/BT-BTech.xlsx', './data/UG/MS-BTech.xlsx']
# following list: find . -name '.*\.xlsx
pg_plist = [
['./data/PG/MTech-3yr/CS-MTech3yr.xlsx', ['curriculum', 'baskets']], # basket is named as elective here. #TODO
['./data/PG/MTech-3yr/ME-MTech3yr.xlsx', ['curriculum']], 
['./data/PG/MTech-3yr/CE-MTech3yr.xlsx', ['curriculum']],
['./data/PG/PhD/MS-PhD.xlsx', ['curriculum', 'baskets']],
['./data/PG/PhD/ME-PhD.xlsx', ['curriculum']],
['./data/PG/PhD/DS-PhD.xlsx', ['curriculum']],
['./data/PG/PhD/CY-PhD.xlsx', ['curriculum']],
['./data/PG/PhD/LA-PhD.xlsx', ['curriculum']],
['./data/PG/PhD/CS-PhD-Direct.xlsx', ['curriculum']],
['./data/PG/PhD/CS-PhD.xlsx', ['curriculum']],
['./data/PG/PhD/CHE-PhD.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/ME-MTech2yr-MAD.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-2yr/CHE-MTech2yr.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/PH-MSc2yr.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/CE-MTech2yr-Geo.xlsx', ['curriculum', 'baskets']], # basket = elective
['./data/PG/MTech-2yr/CY-MSc2yr.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/ME-MTech2yr-FES.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-2yr/CE-MTech2yr-Struct.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-2yr/DS-MDes2yr.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/MS-MTech2yr.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-2yr/EE-MTech2yr-Micro.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/MA-MSc2yr-PhD.xlsx', ['curriculum', 'minor', 'PhD']],
['./data/PG/MTech-2yr/CS-MTech2yr.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/ME-MTech2yr-IDM.xlsx', ['curriculum']],
['./data/PG/MTech-2yr/BT-MTech2yr-PhD.xlsx', []],
['./data/PG/MTech-2yr/CE-MTech2yr-EWRE.xlsx', ['curriculum', 'baskets']], # basket sheet is named as elective.
['./data/PG/MTech-1yr/ME-MTech1yr-MAD.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-1yr/EE-MTech1yr-Micro.xlsx', ['curriculum']],
['./data/PG/MTech-1yr/MS-MTech1yr.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-1yr/MS-MTech1yr-Thesis.xlsx', ['curriculum', 'bakset']],
['./data/PG/MTech-1yr/ME-MTech1yr-IDM.xlsx', ['curriculum']],
['./data/PG/MTech-1yr/CS-MTech1yr-MDS.xlsx', ['curriculum', 'baskets']],
['./data/PG/MTech-1yr/ME-MTech1yr-FES.xlsx', ['curriculum', 'baskets']]
]
ug_plist = [
['./data/UG/LA-BTech.xlsx', ['minor']],
['./data/UG/DS-BDes.xlsx', ['curriculum']],
['./data/UG/PH-BTech.xlsx', ['curriculum', 'baskets', 'minor', 'honors', 'double-major']],
['./data/UG/MA-BTech.xlsx', ['curriculum', 'minor', 'double-major']], # these sheets need proper formatting
['./data/UG/CY-BTech.xlsx', ['curriculum']],  # this file is incomplete.
['./data/UG/EE-BTech.xlsx', ['curriculum']],
['./data/UG/ME-BTech.xlsx', ['curriculum', 'minor', 'honors', 'double-major']],
['./data/UG/MS-BTech.xlsx', ['curriculum', 'baskets', 'minor', 'honors', 'double-major']],
['./data/UG/ES-BTech.xlsx', ['curriculum']],
['./data/UG/CE-BTech.xlsx', ['curriculum', 'baskets', 'minor', 'double-major', 'honors']],
['./data/UG/CHE-BTech.xlsx', ['curriculum', 'baskets', 'minor', 'double-major', 'honors']],
['./data/UG/CS-BTech.xlsx', ['curriculum', 'minor', 'double-major', 'honors']],
['./data/UG/BT-BTech.xlsx', []],
['./data/UG/MS-BTech.xlsx', ['curriculum', 'baskets', 'minor', 'honors', 'double-major']]
]
ug_plist.sort()
